FROM nvcr.io/nvidia/pytorch:24.03-py3

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt update && apt install -y --no-install-recommends \
    software-properties-common \
    curl \
    git \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    libportaudio2 \
    rsync \
    bindfs \
    fuse \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt install -y --no-install-recommends python3.11 python3.11-distutils python3.11-venv \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 \
    && git clone --depth 1 https://github.com/IAHispano/Applio.git /app \
    && rm -rf /app/.git \
    && python3.11 -m pip install --no-cache-dir --upgrade pip \
    && python3.11 -m pip install --no-cache-dir python-ffmpeg \
    && python3.11 -m pip install --no-cache-dir -r /app/requirements.txt --extra-index-url https://download.pytorch.org/whl/cu128 \
    && rm -rf /root/.cache/pip

COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 6969

ENTRYPOINT ["/start.sh"]
