version: '3.8'

services:
  applio:
    image: ghcr.io/cjkihl/applio-runpod:latest
    ports:
      - "6969:6969"
    volumes:
      - runpod-workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  runpod-workspace:
    external: true
    name: runpod-workspace
